# Generated by Django 3.0.5 on 2020-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='invby',
            field=models.IntegerField(default=0),
        ),
    ]
