# Generated by Django 3.0.5 on 2020-05-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestpage', '0002_auto_20200502_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
